# Generated by Django 2.1.1 on 2018-10-07 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='userFollowed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='userSelf',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=420, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userFollowed',
            field=models.ManyToManyField(related_name='userFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
