# Generated by Django 2.1.1 on 2018-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('AndrewID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('SecondName', models.CharField(max_length=200)),
            ],
        ),
    ]
