# Generated by Django 2.1.1 on 2018-10-07 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20181005_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFollowed', models.ManyToManyField(related_name='userFollowed', to=settings.AUTH_USER_MODEL)),
                ('userSelf', models.OneToOneField(on_delete=True, related_name='fan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
