# Generated by Django 2.1.1 on 2018-10-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181007_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='biography',
        ),
    ]
